# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cowrite < Formula
  desc "Vim-flavored terminal markdown editor for co-writing with AI agents"
  homepage "https://github.com/henrypoydar/cowrite"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.1.0/cowrite_0.1.0_darwin_amd64.tar.gz"
      sha256 "521dac2d72614026e7cd4eb7ff3222087df3ffd58025b4246d61f15192812dea"

      define_method(:install) do
        bin.install "cowrite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.1.0/cowrite_0.1.0_darwin_arm64.tar.gz"
      sha256 "ebdd7eb4f99a8012c24ee5be9e12bfcbeaf15f7179b6985ea038b7f912184203"

      define_method(:install) do
        bin.install "cowrite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.1.0/cowrite_0.1.0_linux_amd64.tar.gz"
      sha256 "d335f702ef242879f17127fc2e484b731421f398d5f4d25817b6c41b35391ea2"
      define_method(:install) do
        bin.install "cowrite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.1.0/cowrite_0.1.0_linux_arm64.tar.gz"
      sha256 "49d5fc851d1d9ec5f23637cca516c1244cd9b92d111001fef19162e96e7fa525"
      define_method(:install) do
        bin.install "cowrite"
      end
    end
  end
end
