# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cowrite < Formula
  desc "Vim-flavored terminal markdown editor for co-writing with AI agents"
  homepage "https://github.com/henrypoydar/cowrite"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.1/cowrite_0.2.1_darwin_amd64.tar.gz"
      sha256 "d23131579ab6a73e29841c273d5b4e5ca314535f59597f7938393018508855c0"

      define_method(:install) do
        bin.install "cowrite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.1/cowrite_0.2.1_darwin_arm64.tar.gz"
      sha256 "59e35a633f01291028886de22e0f2c181068cc9be03588e77559cd8baad9c0f5"

      define_method(:install) do
        bin.install "cowrite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.1/cowrite_0.2.1_linux_amd64.tar.gz"
      sha256 "351db1830efd39190055f4005f0e2fc822359c7257f14cbbda1843cc4d37dca1"
      define_method(:install) do
        bin.install "cowrite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.1/cowrite_0.2.1_linux_arm64.tar.gz"
      sha256 "8e4f679ea104224145629a210be8951b3b50842f44eeef17a9fd875ed5ca58fe"
      define_method(:install) do
        bin.install "cowrite"
      end
    end
  end
end
