# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cowrite < Formula
  desc "Vim-flavored terminal markdown editor for co-writing with AI agents"
  homepage "https://github.com/henrypoydar/cowrite"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.0/cowrite_0.2.0_darwin_amd64.tar.gz"
      sha256 "bafc548c37c0af67b7315ea0068b1962150a3591d09c20daf0f41be85e820681"

      define_method(:install) do
        bin.install "cowrite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.0/cowrite_0.2.0_darwin_arm64.tar.gz"
      sha256 "082031a1a0519ef35caad63a31e0e7b1d893a2096b80fb3d46de2eeb1af490e4"

      define_method(:install) do
        bin.install "cowrite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.0/cowrite_0.2.0_linux_amd64.tar.gz"
      sha256 "59e7f0176766c0f51069b67f61d1890cc44553968efef19e4dfc3ac6faf6e9ed"
      define_method(:install) do
        bin.install "cowrite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrypoydar/cowrite/releases/download/v0.2.0/cowrite_0.2.0_linux_arm64.tar.gz"
      sha256 "9e145b920c39df0eac5050e1151b3ace8bbaafc86d2204ac390d167a9b2233ee"
      define_method(:install) do
        bin.install "cowrite"
      end
    end
  end
end
