# This file was generated by GoReleaser. DO NOT EDIT.
cask "cowrite" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "e357ebea00f32665bc75ec7ada290e53900289bf9dcd6db7b55b3fbfb6615144"
      url "https://github.com/henrypoydar/cowrite/releases/download/v#{version}/cowrite_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37175cacdfc247dd928e1f7599492a959de20f80c0b237c4d99582aa61309f15"
      url "https://github.com/henrypoydar/cowrite/releases/download/v#{version}/cowrite_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4d66db3fb6668d158f6a8387e5a43076e037328c6e229fdcff6c3680678ed58"
      url "https://github.com/henrypoydar/cowrite/releases/download/v#{version}/cowrite_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab3830e731d89decb6415d8632ee9f84a438ac78a97ec471c7fae68f11155da1"
      url "https://github.com/henrypoydar/cowrite/releases/download/v#{version}/cowrite_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cowrite"
  desc "Vim-flavored terminal markdown editor for co-writing with AI agents"
  homepage "https://github.com/henrypoydar/cowrite"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cowrite"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cowrite"]
    end
  end

  # No zap stanza required

end
